# fly.toml app configuration file generated for sisukas on 2025-02-15T21:51:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sisukas-test'
primary_region = 'arn'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[statics]]
  guest_path = "/app/dist"
  url_prefix = "/"
  [statics.headers]
    "Cache-Control" = "public, max-age=0, must-revalidate"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
